<?php

namespace app\admin\model;

use app\common\model\BaseModel;

/**
 * 用户行为-模型
 * @package app\admin\model
 */
class Action extends BaseModel
{
    // 设置数据表名
    protected $name = "action";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     */
    public function getInfo($id, $flag = false)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 来源类型
            if ($info['type']) {
                $info['type_name'] = config('admin.action_type')[$info['type']];
            }
            // 执行类型
            if ($info['execution']) {
                $info['execution_name'] = config("admin.action_execution")[$info['execution']];
            }
        }
        return $info;
    }

}
