<?php

namespace app\admin\model;

use app\common\model\BaseModel;

/**
 * 管理员的角色菜单关系-模型类
 * Class AdminRom
 * @package app\admin\model
 */
class AdminRom extends BaseModel
{
    // 设置数据表名
    protected $name = "admin_rom";

    /**
     * 获取缓存信息
     * @param int $id
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function getInfo($id)
    {
        return parent::getInfo($id); // TODO: Change the autogenerated stub
    }

    /**
     * 获取权限菜单
     * @param string $roleIds 角色ID
     * @param int $adminId 用户ID
     * @param int $type 类型
     * @param int $pid 上级ID
     * @return mixed
     */
    public function getPermissionMenu(string $roleIds, int $adminId, int $type, int $pid)
    {
        $map = [];
        if ($roleIds) {
            $map1 = [ // 菜单(权限)分配到具体的角色
                ['r.type', '=', 1], // 角色具有的菜单权限
                ['r.type_id', 'in', $roleIds],
            ];
            $map[] = $map1;
        }
        $map2 = [ // 菜单(权限)直接分配到具体的用户
            ['r.type', '=', 2], // 用户具有的菜单权限
            ['r.type_id', '=', $adminId],
        ];
        $map[] = $map2;
        $menuMod = new Menu();
        $menuList = $menuMod->alias('m')
            ->join(DB_PREFIX . 'admin_rom r', 'r.menu_id=m.id')
            ->distinct(true)
            ->where(function ($query) use ($map) {
                $query->whereOr($map);
            })
            ->where('m.type', '=', $type) // 类型：1模块 2导航 3菜单 4节点，这四种类型存在层级关系
            ->where('m.pid', '=', $pid)
            ->where('m.status', '=', 1)
            ->where('m.mark', '=', 1)
            ->order('m.pid ASC,m.sort ASC')
            ->field('m.*')
            ->select()->toArray();
        if (!empty($menuList)) { // 因为上面存在层级关系，所以，这里需要递归查询下一层级菜单
            $type += 1;
            if ($type <= 4) {
                foreach ($menuList as &$val) {
                    $childList = $this->getPermissionMenu($roleIds, $adminId, $type, $val['id']);
                    if (is_array($childList) && !empty($childList)) {
                        $val['children'] = $childList;
                    }
                }
            }
        }
        return $menuList;
    }

    /**
     * 获取权限节点列表
     * @param string $roleIds 角色ID
     * @param int $adminId 人员ID
     * @return mixed
     */
    public function getPermissionFuncList(string $roleIds, int $adminId)
    {
        $map = [];
        if ($roleIds) { // 存在角色，则
            $map1 = [
                ['r.type', '=', 1], // 角色与菜单关系
                ['r.type_id', 'in', $roleIds],
            ];
            $map[] = $map1;
        }
        $map2 = [
            ['r.type', '=', 2], // 管理员与菜单关系
            ['r.type_id', '=', $adminId],
        ];
        $map[] = $map2;
        $menuMod = new Menu();
        $funcList = $menuMod->alias('m')
            ->join(DB_PREFIX . 'admin_rom r', 'r.menu_id=m.id')
            ->distinct(true)
            ->where(function ($query) use ($map) {
                $query->whereOr($map); // map1 OR map2
            })
            ->where('m.type', '=', 4) // 节点类型
            ->where('m.status', '=', 1)
            ->where('m.mark', '=', 1)
            ->order('m.pid ASC,m.sort ASC')
            ->column('m.permission');
        return $funcList;
    }
}
