<?php

namespace app\admin\model;

use app\common\model\BaseModel;

/**
 * 演示-模型
 * @author lzh
 * @since: 2021/02/06
 * Class Demo3
 * @package app\admin\model
 */
class Demo3 extends BaseModel
{
    // 设置数据表名
    protected $name = "demo3";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author lzh
     * @since: 2021/02/06
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {

            // 头像
            $info['avatar'] = get_image_url($info['avatar']);

        }
        return $info;
    }
}
