<?php

namespace app\admin\model;

use app\common\model\BaseModel;

/**
 * 岗位模型
 * @package app\admin\model
 */
class Position extends BaseModel
{
    // 设置数据表名
    protected $name = "position";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function getInfo(int $id)
    {
        return parent::getInfo($id); // TODO: Change the autogenerated stub
    }
}
