<?php

namespace app\admin\controller;


use app\admin\service\ActionLogService;
use app\common\controller\Backend;

/**
 * 后台操作日志-控制器
 *
 * @property ActionLogService $service
 * @package app\admin\controller
 */
class ActionLog extends Backend
{
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\ActionLog();
        $this->service = new ActionLogService();
    }
}
