<?php

namespace app\admin\controller;


use app\admin\service\AdminService;
use app\common\controller\Backend;
use think\facade\View;

/**
 * 后台管理人员-控制器
 * @package app\admin\controller
 *
 * 类的属性声明指示
 * @property AdminService $service
 */
class Admin extends Backend
{
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Admin();
        /* @var $this->service AdminService */
        $this->service = new AdminService();
    }

    /**
     * 添加或编辑
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function edit()
    {
        // 性别
        View::assign("genderList", config("admin.gender_list"));

        // 角色列表
        $roleMod = new \app\admin\model\Role();
        $roleList = $roleMod->where("mark", 1)->order("sort asc")->select()->toArray();
        View::assign("roleList", $roleList);

        // 职级
        $levelMod = new \app\admin\model\Level();
        $levelList = $levelMod->where("status", 1)->where("mark", 1)->order("sort asc")->select()->toArray();
        View::assign("levelList", $levelList);

        // 岗位
        $positionMod = new \app\admin\model\Position();
        $positionList = $positionMod->where("status", 1)->where("mark", 1)->order("sort asc")->select()->toArray();
        View::assign("positionList", $positionList);

        // 获取上级部门
        $deptMod = new \app\admin\model\Dep();
        $result = $deptMod->getChilds(0, true);
        if ($result) {
            $deptList = array();
            foreach ($result as $val) {
                $key = (int)$val['id'];
                $deptList[$key] = $val;
                $vlist = isset($val['children']) ? $val['children'] : [];
                if ($vlist) {
                    foreach ($vlist as &$v) {
                        $k = (int)$v['id'];
                        $v['name'] = "|--" . $v['name'];
                        $deptList[$k] = $v;
                        $clist = isset($v['children']) ? $v['children'] : [];
                        if ($clist) {
                            foreach ($clist as &$vt) {
                                $kt = (int)$vt['id'];
                                $vt['name'] = "|--|--" . $vt['name'];
                                $deptList[$kt] = $vt;
                            }
                        }
                    }
                }
            }
        }
        // 绑定数据
        View::assign("deptList", $deptList);

        // 获取省份
        $provinceMod = new \app\admin\model\City();
        $provinceList = $provinceMod->where("level", 1)->where("mark", 1)->order("sort asc")->select()->toArray();
        View::assign("provinceList", $provinceList);

        // TODO 如果是POST请求，前面执行属于多余
        return parent::edit(); // TODO: Change the autogenerated stub
    }

    /**
     * 重置密码
     */
    public function resetPwd()
    {
        if (IS_POST) {
            $result = $this->service->resetPwd();
            return $result;
        }
    }
}
