<?php

namespace app\admin\controller;


use app\admin\service\AdminRomService;
use app\common\controller\Backend;

/**
 * 用户与角色关系-控制器
 * Class AdminRom
 *
 * @property AdminRomService $service
 *
 * @package app\admin\controller
 */
class AdminRom extends Backend
{
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //TODO 有点乱，模型不应该在控制器中调用
        $this->model = new \app\admin\model\AdminRom();
        $this->service = new AdminRomService();
    }

    /**
     * 获取菜单列表
     * @return mixed
     */
    public function index()
    {
        $result = $this->service->getList();
        return $result;
    }

    /**
     * 设置权限
     * @return mixed
     */
    public function setPermission()
    {
        $result = $this->service->setPermission();
        return $result;
    }
}
