<?php

namespace app\admin\controller;


use app\admin\service\ConfigGroupService;
use app\common\controller\Backend;

/**
 * 配置分组-控制器
 *
 * @property ConfigGroupService $service
 * @package app\admin\controller
 */
class ConfigGroup extends Backend
{
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\ConfigGroup();
        $this->service = new ConfigGroupService();
    }
}
