<?php

namespace app\admin\controller;


use app\admin\service\DepService;
use app\common\controller\Backend;

/**
 * 部门-控制器
 *
 * @property DepService $service
 * @package app\admin\controller
 */
class Dep extends Backend
{
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Dep();
        $this->service = new DepService();
    }

    /**
     * 删除单条记录
     * @return array
     */
    public function drop()
    {
        if (IS_POST) {
            $id = input('post.id');
            $info = $this->model->getInfo($id);
            if ($info) {
                // 有子级存在则不予删除
                $count = $this->model->getCount([
                    ['pid', '=', $info['id']],
                ]);
                if ($count > 0) {
                    return message("有子级存在，不允许删除", false);
                }
                $result = $this->model->drop($id);
                if ($result !== false) {
                    return message();
                }
            }
            return message($this->model->getError(), false);
        }
    }
}
