<?php

namespace app\admin\controller;

use app\admin\service\AdminRomService;
use app\common\controller\Backend;
use \think\facade\View;
use app\admin\model\Admin;

/**
 * 后台主页控制器
 * @package app\admin\controller
 */
class Index extends Backend
{

    /**
     * 初始化方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new Admin();
    }

    /**
     * 后台主入口
     */
    public function index()
    {
        // 取消模板布局
        $this->app->view->layout(false);

        // 获取导航菜单
        $adminRomService = new AdminRomService();
        $menuList = $adminRomService->getPermissionList($this->adminId);
        View::assign("menuList", $menuList);
        return $this->render();
    }

    /**
     * 欢迎页
     */
    public function main()
    {
        // 取消模板布局
        $this->app->view->layout(false);
        return $this->render();
    }

    /**
     * 个人中心
     */
    public function userInfo()
    {
        if (IS_POST) {
            // 参数
            $param = request()->param();
            // 真实姓名
            $realname = trim($param['realname']);
            // 邮箱
            $email = trim($param['email']);
            // 个人简介
            $intro = trim($param['intro']);
            // 街道地址
            $address = trim($param['address']);
            // 联系电话
            $mobile = trim($param['mobile']);
            $data = [
                'id' => $this->adminId,
                'realname' => $realname,
                'email' => $email,
                'intro' => $intro,
                'address' => $address,
                'mobile' => $mobile,
            ];
            $result = $this->model->edit($data);
            if (!$result) {
                return message("信息保存失败", false);
            }
            return message();
        }
        $adminMod = new Admin();
        $adminInfo = $adminMod->getInfo($this->adminId);
        View::assign("adminInfo", $adminInfo);
        return $this->render();
    }

    /**
     * 更新密码
     */
    public function updatePwd()
    {
        // 参数
        $param = request()->param();
        // 原密码
        $oldPassword = trim($param['oldPassword']);
        if (!$oldPassword) {
            return message("原密码不能为空", false);
        }
        // 新密码
        $newPassword = trim($param['newPassword']);
        if (!$newPassword) {
            return message("新密码不能为空", false);
        }
        // 确认密码
        $rePassword = trim($param['rePassword']);
        if (!$rePassword) {
            return message("确认密码不能为空", false);
        }
        if ($newPassword != $rePassword) {
            return message("两次输入的密码不一致", false);
        }
        if (get_password($oldPassword . $this->adminInfo['username']) != $this->adminInfo['password']) {
            return message("原始密码不正确", false);
        }
        // 设置新密码
        $data = [
            'id' => $this->adminId,
            'password' => get_password($newPassword . $this->adminInfo['username']),
        ];
        $adminMod = new Admin();
        $result = $adminMod->edit($data);
        if (!$result) {
            return message("修改失败", false);
        }
        return message("修改成功");
    }

}
