<?php

namespace app\admin\controller;


use app\admin\service\LevelService;
use app\common\controller\Backend;

/**
 * 职级管理-控制器
 *
 * @property LevelService $service
 * @package app\admin\controller
 */
class Level extends Backend
{
    /**
     * 初始化方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Level();
        $this->service = new LevelService();
    }
}
