<?php

namespace app\admin\controller;


use app\admin\service\PositionService;
use app\common\controller\Backend;

/**
 * 岗位管理-控制器
 * Class Position
 *
 * @property PositionService $service
 * @package app\admin\controller
 */
class Position extends Backend
{
    /**
     * 初始化方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Position();
        $this->service = new PositionService();
    }
}
