<?php

namespace app\admin\controller;


use app\admin\service\RoleService;
use app\common\controller\Backend;

/**
 * 角色管理-控制器
 *
 * @property RoleService $service
 * @package app\admin\controller
 */
class Role extends Backend
{
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Role();
        $this->service = new RoleService();
    }
}
