<?php

namespace app\admin\service;

use app\admin\model\Admin;
use app\admin\model\City;
use app\common\service\BaseService;

/**
 * 人员管理-服务类
 * Class AdminService
 * @package app\admin\service
 */
class AdminService extends BaseService
{
    /**
     * 构造函数
     * @author lzh
     * @since 2020/7/3
     * AdminService constructor.
     */
    public function __construct()
    {
        $this->model = new Admin();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2020/7/11
     * @author lzh
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];

        // 真实姓名
        $realname = isset($param['realname']) ? $param['realname'] : '';
        if ($realname) {
            $map[] = ['realname', 'like', "%{$realname}%"];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2020/7/3
     * @author lzh
     */
    public function edit()
    {
        // 请求参数
        $data = request()->param();
        // 头像处理
        $avatar = isset($data['avatar']) ? trim($data['avatar']) : '';
        if (strpos($avatar, "temp")) { // 临时文件目录
            $data['avatar'] = save_image($avatar, 'admin');
        } else {
            $data['avatar'] = str_replace(IMG_URL, "", $data['avatar']); // 去掉域名
        }
        // 密码加密处理
        $username = trim($data['username']);
        $password = trim($data['password']);
        if ($password) {
            $data['password'] = get_password($password . $username);
        } else {
            unset($data['password']);
        }
        $data['entry_date'] = isset($data['entry_date']) ? strtotime($data['entry_date']) : 0;
        // 保存城市区域
        if ($data['district_id']) {
            $cityMod = new City();
            $cityName = $cityMod->getCityName($data['district_id'], " ");
            $data['city_area'] = $cityName;
        }
        $result = $this->model->edit($data);
        if (!$result) {
            return message("操作失败", false);
        }
        return message();
    }

    /**
     * 重置密码
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function resetPwd()
    {
        $data = request()->param();
        $adminId = (int)$data['id'];
        $info = $this->model->getInfo($adminId);
        if (!$info) {
            return message('当前用户信息不存在', false);
        }
        $data['password'] = get_password("123456" . $info['username']);
        return parent::edit($data);
    }
}
