<?php

namespace app\admin\service;

use app\admin\model\AdSort;
use app\common\service\BaseService;

/**
 * 广告位管理-服务类
 * @author lzh
 * @since 2020/7/2
 * Class AdSortService
 * @package app\admin\service
 */
class AdSortService extends BaseService
{
    /**
     * 构造函数
     * @author lzh
     * @since 2020/7/2
     * AdSortService constructor.
     */
    public function __construct()
    {
        $this->model = new AdSort();
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2021/1/24
     * @author lzh
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
        // 站点栏目
        $itemArr = explode(",", $data['cate_id']);
        if (!empty($itemArr)) {
            $data['item_id'] = $itemArr[0]; // 站点id
            $data['cate_id'] = $itemArr[1]; // 栏目id
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

}
